### PR TITLE
specify butter cms version, fixes webpack error

### PR DESCRIPTION
**Pull request by grantglidewell**

### CODE REVIEW

**Comment by jakelumetta** [comment]
@ggcadc What error were you running into that this change fixes?

**Comment by grantglidewell** [comment]
`ERROR in ./~/buttercms/package.json
Module parse failed: ./react-ssr-example/node_modules/buttercms/package.json Unexpected token (2:9)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:9)`

**Comment by jakelumetta** [comment]
@ggcadc  That error seems to be an inability to parse JSON. However I'm not seeing how the original `package.json` contained invalid JSON.  `^` is valid character when inside of a string. You'll notice other packages also start with `^`

**Comment by grantglidewell** [comment]
ok, The package.json it's finding an error in is the 1.1.0 version of buttercms(not the project package.json), specifying the exact 1.0.15 fixes the issue. it's likely there is another fix, and another issue at the core, this is what fixed it temporarily for me, as the ^ symbol will install any version available above the stated version in the package.

**Comment by jakelumetta** [comment]
Thanks @ggcadc . Will look into the js sdk itself.  closing this issue for now.

**Pull request closed without merging**
